baseurl = "https://gglee4ai.github.io/blog/"
languageCode = "ko-kr"
title = "gglee Blog"
theme = "hugo-xmin"
googleAnalytics = "UA-162930875-1"
disqusShortname = "gglee-blog"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
publishDir = "docs"
preserveTaxonomyNames = true   # add by gglee
hasCJKLanguage = true          # add by gglee
DefaultContentLanguage = "ko"  # add by gglee

[permalinks]
    post = "/post/:year/:slug/"
    # note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
# [[menu.main]]
#     name = "Subscribe"
#     url = "/index.xml"

[params]
    description = "이 사이트는 Hugo와 blogdown으로 제작되었습니다."
    footer = "&copy; [gglee](https://gglee4ai.github.io) 2020  | [Github](https://github.com/gglee4ai)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
