baseurl = "/"
languageCode = "ko-kr"
title = "gglee blog"
theme = "hugo-xmin"
googleAnalytics = "UA-162930875-1"
disqusShortname = "gglee-blog"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
publishDir = "docs"            # gglee for github page
relativeURLs = true            # gglee for github.io/blog
# canonifyURLs = false         # gglee, default for blogdown
hasCJKLanguage = true          # gglee for korean language
DefaultContentLanguage = "ko"  # gglee for korean language


[permalinks]
    post = "/post/:year/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
# [[menu.main]]
#     name = "Subscribe"
#     url = "/index.xml"

[params]
    description = "이 사이트는 Hugo와 blogdown으로 제작되었습니다."
    footer = "&copy; [gglee](https://gglee4ai.github.io) 2020  | [Github](https://github.com/gglee4ai)"
    autonumbering = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokailight"
    # style = "monokai" # default